# Place Installation Parameters for local testing.
# For eg., if you have defined `username` in your
# `iparam_en.yml`, you can define the value here:
# username: YOUR_INSTALLED_USERS_USERNAME

freshdesk_apikey: m6OXOcoOC52a0Z65X9x
